---
apiVersion: v1
kind: Pod
metadata:
  name: sinus-music-pod
  labels:
    app: sinus-music-pod
spec:
  volumes:
    - name: sinus-music-volume-data
      hostPath:
        path: /mnt/Dreamer/container/sinusbot/data
        type: DirectoryOrCreate
    - name: sinus-music-volume-scripts
      hostPath:
        path: /mnt/Dreamer/container/sinusbot/scripts
        type: DirectoryOrCreate
  containers:
    - name: sinus-music
      image: sinusbot/docker
      env:
       - name: UID
         value: "1000"
       - name: GID
         value: "1000"
      ports:
        - containerPort: 8087
      volumeMounts:
        - name: sinus-music-volume-data
          mountPath: /opt/sinusbot/data
        - name: sinus-music-volume-scripts
          mountPath: /opt/sinusbot/scripts
---
apiVersion: v1
kind: Service
metadata:
  name: sinus-music-svc
spec:
  type: ClusterIP
  selector:
    app: sinus-music-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8087
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sinus-music-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "public"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-body-size: "1g"
spec:
  tls:
  - hosts:
    - music.tvonsegg.com
    secretName: tvonsegg-sinus-music-tls
  rules:
    - host: music.tvonsegg.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sinus-music-svc
                port:
                  number: 80
